/**
 * Client-safe audit enums.
 * Duplicated from Prisma schema to avoid importing @prisma/client in client components,
 * which pulls in node:fs and breaks the webpack build.
 */

export const AuditEvent = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_REGISTERED: 'USER_REGISTERED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  WORKSPACE_CREATED: 'WORKSPACE_CREATED',
  WORKSPACE_UPDATED: 'WORKSPACE_UPDATED',
  WORKSPACE_DELETED: 'WORKSPACE_DELETED',
  WORKSPACE_SETTINGS_CHANGED: 'WORKSPACE_SETTINGS_CHANGED',
  MEMBER_INVITED: 'MEMBER_INVITED',
  MEMBER_JOINED: 'MEMBER_JOINED',
  MEMBER_REMOVED: 'MEMBER_REMOVED',
  MEMBER_ROLE_CHANGED: 'MEMBER_ROLE_CHANGED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',
  DOCUMENT_UPDATED: 'DOCUMENT_UPDATED',
  DOCUMENT_PROCESSED: 'DOCUMENT_PROCESSED',
  DOCUMENT_PROCESSING_FAILED: 'DOCUMENT_PROCESSING_FAILED',
  CHAT_CREATED: 'CHAT_CREATED',
  CHAT_UPDATED: 'CHAT_UPDATED',
  CHAT_DELETED: 'CHAT_DELETED',
  CHAT_MESSAGE_SENT: 'CHAT_MESSAGE_SENT',
  API_KEY_CREATED: 'API_KEY_CREATED',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  API_KEY_USED: 'API_KEY_USED',
  RATE_LIMIT_HIT: 'RATE_LIMIT_HIT',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  AGENT_QUERY_CLASSIFIED: 'AGENT_QUERY_CLASSIFIED',
  AGENT_TOOL_CALLED: 'AGENT_TOOL_CALLED',
  MULTI_STEP_REASONING_STARTED: 'MULTI_STEP_REASONING_STARTED',
  CONVERSATION_BRANCHED: 'CONVERSATION_BRANCHED',
  VOICE_TRANSCRIPTION: 'VOICE_TRANSCRIPTION',
  READ_API_USAGE: 'READ_API_USAGE',
  ENCRYPTION_OPERATION: 'ENCRYPTION_OPERATION',
} as const;

export type AuditEvent = (typeof AuditEvent)[keyof typeof AuditEvent];

export const AuditSeverity = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
  CRITICAL: 'CRITICAL',
} as const;

export type AuditSeverity = (typeof AuditSeverity)[keyof typeof AuditSeverity];
